# Generated by Django 6.1 on 2026-08-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='alert_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
