# Generated by Django 6.1 on 2026-08-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0002_activitylog_alert_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted'), ('DATA_ACCESS', 'Resource/Data Viewed'), ('ACCESS_DENIED', 'Access Denied / Permission Error'), ('SYSTEM_ERROR', 'System / Server Error')], default='VIEW', max_length=20),
        ),
    ]
