# Generated by Django 6.1 on 2026-08-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0003_alter_activitylog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='nepali_time',
            field=models.CharField(blank=True, editable=False, max_length=19),
        ),
    ]
