# Generated by Django 6.1 on 2026-08-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0004_activitylog_nepali_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='nepali_time',
        ),
    ]
