# Generated by Django 6.1 on 2026-08-21 10:59

import setting_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0005_remove_activitylog_nepali_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='nepali_time',
            field=models.CharField(blank=True, editable=False, max_length=19),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(default=setting_app.models.kathmandu_now),
        ),
    ]
