# Generated by Django 6.0 on 2026-09-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0006_activitylog_nepali_time_alter_activitylog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted'), ('DATA_ACCESS', 'Resource/Data Viewed'), ('ACCESS_DENIED', 'Access Denied / Permission Error'), ('SYSTEM_ERROR', 'System / Server Error'), ('VIEW', 'Page Access')], default='VIEW', max_length=20),
        ),
    ]
