# Generated by Django 6.1 on 2026-09-06 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_sale_received_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('FONEPAY_QR', 'Fonepay QR'), ('CREDIT', 'Credit')], max_length=20)),
                ('provider', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'),  ('FONEPAY', 'Fonepay'), ('INTERNAL', 'Internal')], default='INTERNAL', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=150, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('qr_data', models.TextField(blank=True, null=True)),
                ('qr_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.sale')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='FonepayTransaction',
            fields=[
                ('fonepay_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('merchant_code', models.CharField(max_length=100)),
                ('transaction_reference', models.CharField(max_length=150, unique=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qr_payload', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='CREATED', max_length=20)),
                ('response_code', models.CharField(blank=True, max_length=50, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fonepay_transaction', to='payments.payment')),
            ],
            options={
                'db_table': 'fonepay_transaction',
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('refund_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_reference', models.CharField(max_length=100, unique=True)),
                ('provider_refund_id', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'db_table': 'payment_refund',
            },
        ),
    ]
