# Generated by Django 6.0 on 2026-09-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('sales', '0003_alter_sale_options_alter_saleitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='expires_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='narration',
            new_name='failure_reason',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_reference',
            new_name='internal_reference',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='qr_data',
            new_name='qr_payload',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='qr_expiry',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('FONEPAY', 'Fonepay'), ('CARD', 'Card'), ('BANK', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment_transaction',
        ),
    ]
