# Generated by Django 6.1 on 2026-09-07 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_options_remove_payment_expires_at_and_more'),
    ]

    operations = [
       
    ]
