# Generated by Django 6.1 on 2026-09-07 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_options_remove_payment_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='fonepaytransaction',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('CASH', 'Cash'),
                    ('CARD', 'Card / POS'),
                    ('BANK_TRANSFER', 'Bank Transfer'),
                    ('FONEPAY', 'Fonepay QR'),
                    
                    ('CREDIT', 'On Credit'),
                    ('SPLIT', 'Split Payment'),
                ],
                max_length=20,
            ),
        ),
    ]
