# Generated by Django 6.0 on 2026-09-25 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_refund_credit_memo'),
        ('purchases', '0007_purchasedetail_batch_no'),
        ('sales', '0006_sale_journal_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonepaytransaction',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='internal_reference',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card / POS'), ('FONEPAY', 'Fonepay QR'), ('CREDIT', 'On Credit'), ('SPLIT', 'Split Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payments', to='purchases.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PROCESSING', 'Processing Payment'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid / Settled'), ('FAILED', 'Payment Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sale__isnull', False), ('purchase__isnull', True)), models.Q(('sale__isnull', True), ('purchase__isnull', False)), _connector='OR'), name='payment_exactly_one_party'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_positive_amount'),
        ),
        migrations.DeleteModel(
            name='FonepayTransaction',
        ),
    ]
