# Generated by Django 6.0 on 2026-09-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('uom_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=50, unique=True)),
                ('notation', models.CharField(max_length=10)),
                ('is_weight_based', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'unit_of_measure',
                'managed': False,
            },
        ),
    ]
