# Generated by Django 6.0 on 2026-08-22 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('suppliers', '0002_supplier_is_active'),
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('variant_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'product_variant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('order_date', models.DateField()),
                ('received_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tds_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_payable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_by_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_orders', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'purchase_order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('purchase_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('particular', models.CharField(max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('ordered_quantity', models.DecimalField(db_comment='Qty requested', decimal_places=3, max_digits=10)),
                ('agreed_unit_price', models.DecimalField(db_comment='Initial PO price', decimal_places=2, max_digits=10)),
                ('received_quantity', models.DecimalField(blank=True, db_comment='Actual catch-weight received', decimal_places=3, max_digits=10, null=True)),
                ('actual_unit_price', models.DecimalField(blank=True, db_comment='Price charged on final supplier invoice', decimal_places=2, max_digits=10, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchases.productvariant')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchases.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_detail',
                'managed': True,
            },
        ),
    ]
