# Generated by Django 6.0 on 2026-09-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetail',
            name='particular',
        ),
    ]
