# Generated by Django 6.1 on 2026-09-06 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('purchases', '0002_remove_purchasedetail_particular'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.journalentry'),
        ),
    ]
