# Generated by Django 6.0 on 2026-09-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchaseorder_freight_and_settlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='freight_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
