# Generated by Django 6.0 on 2026-09-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_supplier_response_vendor_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
