# Generated by Django 6.1 on 2026-08-15 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('MANAGER', 'manager'), ('STAFF', 'staff'), ('SUPPLIER', 'supplier')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('dashboard', 'Dashboard'), ('accounts', 'User & Accounts Management'), ('categories', 'Categories'), ('products', 'Products'), ('suppliers', 'Suppliers'), ('customers', 'Customers'), ('sales', 'Sales'), ('inventory', 'Inventory')], max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions', to='accounts.role')),
            ],
            options={
                'unique_together': {('role', 'module_name')},
            },
        ),
    ]
