# Generated by Django 6.0 on 2026-09-01 16:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_change', models.DecimalField(decimal_places=3, help_text='Negative for loss (-2.000), positive for audit addition (+2.000)', max_digits=10)),
                ('reason_code', models.CharField(choices=[('EXPIRED', 'Stock Expired'), ('DAMAGED', 'Damaged / Broken'), ('THEFT', 'Stolen / Missing'), ('CORRECTION', 'Inventory Audit Correction'), ('RETURN', 'Returned Goods Adjustment')], max_length=20)),
                ('loss_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_adjustment',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=50)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(db_index=True)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('current_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXHAUSTED', 'Exhausted'), ('EXPIRED', 'Expired'), ('QUARANTINED', 'Quarantined / Hold')], db_index=True, default='ACTIVE', max_length=20)),
                ('purchase_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchasedetail')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='products.productvariant')),
            ],
            options={
                'db_table': 'inventory_batch',
                'ordering': ['expiry_date', 'received_date'],
            },
        ),
    ]
