# Generated by Django 6.1 on 2026-09-06 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockadjustment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.journalentry'),
        ),
    ]
