# Generated by Django 6.1 on 2026-09-06 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockadjustment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
       
        
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_change',
            field=models.DecimalField(decimal_places=3, help_text='Negative for write-off (-2.000), positive for audit gain (+2.000)', max_digits=10),
        ),
    ]
