# Generated by Django 6.1 on 2026-09-06 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockadjustment_adjusted_by_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
      
        migrations.AddField(
            model_name='stockadjustment',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.inventorybatch'),
            preserve_default=False,
        ),
    ]
