# Generated by Django 6.1 on 2026-09-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchasereturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('EXPIRED', 'Stock Expired'), ('DAMAGED', 'Damaged / Broken'), ('THEFT', 'Stolen / Missing'), ('CORRECTION', 'Inventory Audit Correction'), ('RETURN', 'Returned Goods Adjustment'), ('WASTAGE', 'Wastage')], max_length=50, null=True),
        ),
    ]
