# Generated by Django 6.0 on 2026-09-17 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stockadjustment_reason_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='inventorybatch',
            name='batch_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXHAUSTED', 'Depleted / Closed'), ('EXPIRED', 'Expired'), ('QUARANTINED', 'Quarantined / Hold')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
