# Generated by Django 6.0 on 2026-09-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('requires_expiry_tracking', models.BooleanField(blank=True, null=True)),
                ('requires_batch_tracking', models.BooleanField(blank=True, null=True)),
                ('requires_catch_weight', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
