# Generated by Django 6.1 on 2026-09-07 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_fiscalyear_bs_year_remove_fiscalyear_end_date_and_more'),
        ('customers', '0002_customer_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customerscheme',
            options={},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={},
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_vat_number',
            field=models.CharField(blank=True, help_text='IRD PAN/VAT number for Tax Billing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ledgers', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
