# Generated by Django 6.1 on 2026-09-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastages',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
