# Generated by Django 6.1 on 2026-09-06 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fiscal_year',
               
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_code', models.CharField(max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='accounting.account')),
            ],
            options={
                'db_table': 'account',
               
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference_type', models.CharField(choices=[('SALE', 'Sales Invoice'), ('PURCHASE', 'Purchase Order'), ('ADJUST', 'Stock Adjustment/Wastage'), ('PAYMENT', 'Payment Settlement'), ('MANUAL', 'Manual Journal Voucher')], max_length=10)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('fiscal_year', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_entry',
             
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'journal_item',
            
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], max_length=10)),
                ('payment_mode', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
            ],
            options={
                'db_table': 'payment_receipt',
              
            },
        ),
    ]
