# Generated by Django 6.1 on 2026-09-06 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreceipt',
            options={},
        ),
      
       
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.payment'),
           
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='receipt_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='party_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
