# Generated by Django 6.1 on 2026-09-06 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_paymentreceipt_options_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.payment'),
        ),
    ]
