# Generated by Django 6.0 on 2026-09-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_paymentreceipt_supplier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'ordering': ['-bs_year']},
        ),
        
        migrations.AddField(
            model_name='fiscalyear',
            name='bs_year',
            field=models.IntegerField(default=1, help_text='Starting Bikram Sambat year (e.g., 2081 for FY 2081/82)', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Currently active fiscal year for system operations'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Closed fiscal years lock accounting entries'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='name',
            field=models.CharField(blank=True, help_text='Format: 2081/82', max_length=20, unique=True),
        ),
    ]
