# Generated by Django 6.0 on 2026-09-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_fiscalyear_options_remove_fiscalyear_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'ordering': ['-start_date_bs']},
        ),
        
        migrations.AddField(
            model_name='fiscalyear',
            name='end_date_bs',
            field=models.CharField(default=1, help_text='YYYY-MM-DD (Ashadh End)', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='start_date_bs',
            field=models.CharField(default=1, help_text='YYYY-MM-DD (Shrawan 1)', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='name',
            field=models.CharField(help_text='Format: 2080/81', max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='fiscalyear',
            table=None,
        ),
    ]
