# Generated by Django 6.1 on 2026-09-07 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_fiscalyear_options_remove_fiscalyear_bs_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
       
        migrations.AddField(
            model_name='journalentry',
            name='bs_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('SALE', 'Sales Invoice'), ('PURCHASE', 'Purchase Order'), ('ADJUST', 'Stock Adjustment/Wastage'), ('PAYMENT', 'Payment Settlement'), ('EXPENSE', 'Expense Voucher'), ('MANUAL', 'Manual Journal Voucher')], max_length=10),
        ),
    ]
