# Generated by Django 6.0 on 2026-09-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_paymentreceipt_supplier'),
    ]

    operations = [
        
    ]
