# Generated by Django 6.0 on 2026-09-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_paymentreceipt_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalyear',
            name='bs_year',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='start_date',
        ),
    ]
