# Generated by Django 6.0 on 2026-09-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_journalentry_status_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalyear',
            name='bs_year',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='start_date',
        ),
    ]
