# Generated by Django 6.1 on 2026-09-06 22:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_paymentreceipt_options_and_more'),
        ('sales', '0002_sale_received_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date']},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={},
        ),
     
        
        
        migrations.AlterField(
            model_name='sale',
            name='tender_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
