# Generated by Django 6.1 on 2026-09-07 19:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       
        ('sales', '0003_alter_sale_options_alter_saleitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='customer_pan',
            new_name='buyer_pan',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='change_amount',
            new_name='due_amount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='received_amount',
            new_name='paid_amount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='sales_id',
            new_name='sale_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='narration',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='round_off',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tender_amount',
        ),
        
        migrations.AlterField(
            model_name='sale',
            name='bs_date',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card / POS'), ('BANK_TRANSFER', 'Bank Transfer'), ('FONEPAY', 'Fonepay QR'), ('ESEWA', 'eSewa Wallet'), ('KHALTI', 'Khalti Wallet'), ('SPLIT', 'Split Payment')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid / Settled'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_ac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_records', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='vat_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
