# Generated by Django 6.0 on 2026-09-25 05:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_remove_fiscalyear_bs_year_remove_fiscalyear_end_date_and_more'),
        ('customers', '0002_alter_customer_options_alter_customerscheme_options_and_more'),
        ('inventory', '0012_inventorybatch_batch_no_and_more'),
        ('products', '0001_initial'),
        ('sales', '0006_sale_journal_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer_pan',
        ),
        migrations.AddField(
            model_name='sale',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Required for new sales; legacy rows are backfilled during migration.', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='sale',
            name='grand_total_in_words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='bs_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card / POS'), ('FONEPAY', 'Fonepay QR'), ('CREDIT', 'On Credit'), ('SPLIT', 'Split Payment')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PROCESSING', 'Processing Payment'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid / Settled'), ('FAILED', 'Payment Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='round_off',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_CREDITED', 'Partially Credited'), ('FULLY_CREDITED', 'Fully Credited')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_ac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_records', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='vat_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('discount_total__gte', 0), ('taxable_amount__gte', 0), ('non_taxable_amount__gte', 0), ('vat_total__gte', 0), ('grand_total__gte', 0), ('paid_amount__gte', 0), ('due_amount__gte', 0)), name='sale_non_negative_totals'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_item_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sale_item_non_negative_price'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='sale_item_non_negative_discount'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('vat_percent__gte', 0)), name='sale_item_non_negative_vat_percent'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('net_subtotal__gte', 0), ('line_total__gte', 0)), name='sale_item_non_negative_totals'),
        ),
    ]
