# Generated by Django 6.0 on 2026-09-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(max_length=150)),
                ('is_organic', models.BooleanField(default=False)),
                ('is_eco_friendly', models.BooleanField(default=False)),
                ('shelf_life_days', models.IntegerField(blank=True, help_text='Typical shelf life in days', null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('variant_name', models.CharField(max_length=150)),
                ('is_catch_weight', models.BooleanField(default=False)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_vatable', models.BooleanField(default=False)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=10.0, max_digits=10)),
                ('target_stock_level', models.DecimalField(decimal_places=3, default=50.0, max_digits=10)),
                ('abc_class', models.CharField(blank=True, choices=[('A', 'High Value'), ('B', 'Medium Value'), ('C', 'Low Value')], max_length=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_variant',
                'managed': False,
            },
        ),
    ]
